### ISSUE TITLE
FYI: everything in single Vagrantfile

### ISSUE THREAD

**Issue by ngerstle** [ltpitt/vagrant-cloudpebble-composed#1]
Just an FYI- I wrapped what you've done into a single Vagrant file for ease of use.
Don't know if it's handy for you, but might be handy for some.

https://github.com/ngerstle/cloudpebble-vagrantfile/blob/master/Readme.md

Feel free to ignore, and thanks for the help.

**Comment by ltpitt** [comment]
Simply amazing, @ngerstle !

The work is not complete yet (installation steps need cleaning and a few features are still broken) but I will indeed use your work as a start to make a final, sleek, easy, working one.

Really thanks 👍
